create table if not exists public.intake_requests (
  id bigint generated by default as identity primary key,
  form_type text not null,
  source_page text,
  contact_email text,
  contact_phone text,
  payload jsonb not null,
  submitted_at timestamptz,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

alter table public.intake_requests enable row level security;

grant usage on schema public to anon, authenticated;
grant insert on table public.intake_requests to anon, authenticated;
grant select, update on table public.intake_requests to authenticated;
grant usage, select on sequence public.intake_requests_id_seq to anon, authenticated;

drop policy if exists "anon can insert intake" on public.intake_requests;
create policy "anon can insert intake"
on public.intake_requests
for insert
to anon
with check (true);

drop policy if exists "authenticated can insert intake" on public.intake_requests;
create policy "authenticated can insert intake"
on public.intake_requests
for insert
to authenticated
with check (true);

drop policy if exists "public can insert intake" on public.intake_requests;
create policy "public can insert intake"
on public.intake_requests
for insert
to public
with check (true);

drop policy if exists "authenticated can read intake" on public.intake_requests;
create policy "authenticated can read intake"
on public.intake_requests
for select
to authenticated
using (true);

drop policy if exists "authenticated can update intake" on public.intake_requests;
create policy "authenticated can update intake"
on public.intake_requests
for update
to authenticated
using (true)
with check (true);

create table if not exists public.portal_tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  owner text,
  due_date date,
  notes text,
  status text not null default 'open',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.portal_tasks enable row level security;

grant select, insert, update on table public.portal_tasks to authenticated;
grant usage, select on sequence public.portal_tasks_id_seq to authenticated;

drop policy if exists "authenticated can read tasks" on public.portal_tasks;
create policy "authenticated can read tasks"
on public.portal_tasks
for select
to authenticated
using (true);

drop policy if exists "authenticated can insert tasks" on public.portal_tasks;
create policy "authenticated can insert tasks"
on public.portal_tasks
for insert
to authenticated
with check (true);

drop policy if exists "authenticated can update tasks" on public.portal_tasks;
create policy "authenticated can update tasks"
on public.portal_tasks
for update
to authenticated
using (true)
with check (true);
