create table if not exists public.intake_requests (
  id bigint generated by default as identity primary key,
  form_type text not null,
  source_page text,
  contact_email text,
  contact_phone text,
  payload jsonb not null,
  submitted_at timestamptz,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

alter table public.intake_requests enable row level security;

drop policy if exists "anon can insert intake" on public.intake_requests;
create policy "anon can insert intake"
on public.intake_requests
for insert
to anon
with check (true);

drop policy if exists "authenticated can read intake" on public.intake_requests;
create policy "authenticated can read intake"
on public.intake_requests
for select
to authenticated
using (true);

drop policy if exists "authenticated can update intake" on public.intake_requests;
create policy "authenticated can update intake"
on public.intake_requests
for update
to authenticated
using (true)
with check (true);
